// guides/reactivity/book/introduction/cells-and-formulas/in-vue.vue
<script>
import { use } from "@starbeam/vue";
import { LiterCounter } from "#reactive/liter-counter";

export default {
  setup() {
    const { increment, description } = use(LiterCounter);

    return { increment, description };
  },
};
</script>

<template>
  <button v-on:click="increment">Add a liter</button>
  <p>{description}</p>
</template>

// guides/reactivity/src/introduction/cells-and-formulas/in-react.tsx
import { LiterCounter } from "#reactive/liter-counter";
import { use } from "@starbeam/react";

export function LiterLikeButton() {
  const liters = use(LiterCounter);

  return (
    <>
      <button onClick={() => liters.increment()}>Add a liter</button>
      <p>{liters.description}</p>
    </>
  );
}
